### ISSUE TITLE
InvalidOperationException executing Equation Page in sample

### ISSUE THREAD

**Issue by lenj962** [limefrogyank/MathJaxBlazor#2]
I downloaded the demo source and ran the MathJaxBlazor.Demo project.  When I clicked the Equation link I got an InvalidOperationException:

System.InvalidOperationException: Cannot provide a value for property 'ThemeProvider' on type 'BlazorFabric.TextField'. There is no registered service of type 'BlazorFabric.ThemeProvider'.

Further research seems to direct toward using BlazorFluentUI (v. 3.1.2).

How should this be addressed?

Thanks,
Leonard

**Comment by limefrogyank** [comment]
I made this demo back before we refactored the UI library I used.  It *might* work if you downgrade BlazorFabric to what the demo was originally compiled with... seems to be 2.0.1.  However, those also were made using preview packages of blazor.  So it might not work.  

I might redo this demo sometime in the future, but I'd accept a pull request if you want to try.  You can either strip out all of the BlazorFabric stuff and just use Bootstrap or upgrade to the latest BlazorFluentUI (we renamed it).

Might be easier just to strip out the BlazorFabric stuff.  I just wanted to see how it looked in some of the components I built.

**Comment by limefrogyank** [comment]
I updated the entire thing and removed the dependency on BlazorFluentUI / BlazorFabric.  It should work fine now.
