### ISSUE TITLE
Parts of text remains when data changes

### ISSUE THREAD

**Issue by fredrikbaberg** [limefrogyank/MathJaxBlazor#3]
I just saw this which seems like a nice way to get properly formatted equations. Unfortunately I encountered some issues.

The case I want to use it for is formatting an equation inside a text string. The equation is separated by `$`, e.g. `What is $ x+2 $?`. The `<Equation>` component does not seem correct as it formats everything, so I used `@inherits MathJaxContentComponent` as in the documentation. This renders it properly, but when data changes there are still parts of the previous text visible.

I noticed an error in the browser console, which may or may not be related.  In any case I assume it should not happen.

```
TypeError: MathJax.startup.document.math.toArray is not a function
    at Object.undoTypset (mathJaxBlazor.js:22)
    at Object.typesetClear (mathJaxBlazor.js:42)
    at mathJaxBlazor.js:34
```

I am currently testing this on .NET 6 RC1. The code is moved to a separate component so that not all text is affected:

```razor
@inherits MathJaxContentComponent

@Text

@code
{
    [Parameter]
    public string? Text { get; set; }
    [Parameter]
    public EventCallback<string> TextChanged { get; set; }
}
```

**Comment by limefrogyank** [comment]
This code was written in asp net core 3 days. While Equation should work in general, the other component was truly a hack. MathJax changes the DOM and blazor works by knowing what's different.  They are basically incompatible technologies. My hack would undo the MathJax changes before every blazor render and redo them afterwards. It might not work with newer versions of blazor... I haven't tried lately.

**Comment by limefrogyank** [comment]
I should say if you want to fix it and do a PR, I'll accept it and republish the nuget package.

**Comment by fredrikbaberg** [comment]
Ok, thank you for the quick reply.

I tried to change
> MathJax.startup.document.math.toArray()
to
> Array.from(MathJax.startup.document.math)

This seems to remove the error in the console (not fully tested), but I have the same issue with old text remaining. If I figure something out I'll do a PR.

**Comment by ridwandwiseptian** [comment]
Thanks for @limefrogyank MathJaxBlazor.
I've tried it and it works. 

I have one question, when i add the question back it loops.
Like this :
![1](https://user-images.githubusercontent.com/35426663/154162855-a380273b-90b4-437c-b02f-1b46afeb4e61.png)

same like https://yellow-grass-06f48d51e.azurestaticapps.net/equationPage
![2](https://user-images.githubusercontent.com/35426663/154162894-80a95648-3541-478b-b4ad-2da8bcac9841.png)


can u help me  to avoid looping on the page?

thanks...

**Comment by limefrogyank** [comment]
I've fixed everything.... but you'll need an upgrade to net6 to use it all.  If you can't do that, you can see the changes I made in the typescript file.  Mostly it's the same as the original javascript file (except for all the interface definitions).  There's one big change that involves that section you were looking at.
